In [1]:
import pickle

with open("titanic_step2_feature_add.pickle","rb") as pickle_filename : 
    df = pickle.load(pickle_filename)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,Fare,Cabin,Embarked,Family,Ticket_Initial2,Ticket_Num_Cut,Initial,HighChance,LowChance
0,1,0.0,3,"Braund, Mr. Owen Harris",male,3.0,0.0,0,S,2,0,3,0,0,0
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,4.0,3.0,1,C,2,1,3,2,2,0
2,3,1.0,3,"Heikkinen, Miss. Laina",female,3.0,0.0,0,S,1,2,9,1,0,0
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,4.0,2.0,1,S,2,3,5,2,2,0
4,5,0.0,3,"Allen, Mr. William Henry",male,4.0,0.0,0,S,1,3,9,0,0,0

In [ ]:
#지금까지 우리가 해왔던 주요내용
# 1)EDA
# 2)Feature Engineering (0,1,2,~11) 
#문제제기 :  특정 모델들 중에서는 Feature Engineering (수치화되어진 수ㄴ자 => 의미 존재 x)


#label encoding 
#: 기존의 값을 전통적인 Feature Engineering 작업을 통해서 큰 의미부여 없이 수치화된 값으로 범주를 분류

#Linear Regression (선형회귀)모델 , Feature Engineering 작업 -> encoding->원하지 않는 예측, 결과 값

#onehot encoding
#각 피처마다 입력된 수치 범주값을 확인. 확인된 개수만큼을 피벗테이블처럼 열 수를 생성한 후 해당열에 속하면 1, 그렇지 않으면 0을 부여하는 것

In [6]:
import pandas as pd

train = pd.read_csv("titanic/train.csv")
test = pd.read_csv("titanic/test.csv")

ntrain = train.shape[0]
ntest = test.shape[0]

In [7]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df = train.copy()

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df["Cabin"] = df["Cabin"].fillna("U")

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U,S

In [13]:
df["Cabin"] = df["Cabin"].str[0]  #1번째 문자열을 추출해서 다시 cabin값으로 재할당하기

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U,S

In [16]:
df["Cabin"].unique()

array(['U', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [19]:
df[df["Cabin"] =="U"]["Ticket"]

0             A/5 21171
2      STON/O2. 3101282
4                373450
5                330877
7                349909
             ...
884     SOTON/OQ 392076
885              382652
886              211536
888          W./C. 6607
890              370376
Name: Ticket, Length: 687, dtype: object

In [41]:
import pickle

with open("titanic_step2_feature_add.pickle","rb") as pickle_filename : 
    df = pickle.load(pickle_filename)

In [42]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,1,0.0,3,0,3.0,0.0,0,0,0,2,0,3,0,0
1,2,1.0,1,1,4.0,3.0,1,1,2,2,1,3,2,0
2,3,1.0,3,1,3.0,0.0,0,0,1,1,2,9,0,0
3,4,1.0,1,1,4.0,2.0,1,0,2,2,3,5,2,0
4,5,0.0,3,0,4.0,0.0,0,0,0,1,3,9,0,2

In [43]:
df_label = df.copy()
df_onehot = df.copy()

In [44]:
df_label.shape

(1309, 14)

In [45]:
ntrain

891

In [46]:
train = df[:ntrain]

In [47]:
train.shape

(891, 14)

In [48]:
y_train = train[["Survived"]].copy()

In [31]:
y_train.head()

   Survived
0       0.0
1       1.0
2       1.0
3       1.0
4       0.0

In [49]:
df_label.head()

,PassengerId,Survived,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,1,0.0,3,0,3.0,0.0,0,0,0,2,0,3,0,0
1,2,1.0,1,1,4.0,3.0,1,1,2,2,1,3,2,0
2,3,1.0,3,1,3.0,0.0,0,0,1,1,2,9,0,0
3,4,1.0,1,1,4.0,2.0,1,0,2,2,3,5,2,0
4,5,0.0,3,0,4.0,0.0,0,0,0,1,3,9,0,2

In [50]:
drop_features = ["PassengerId", "Survived"]
df_label = df_label.drop(drop_features, axis=1).copy()
df_label.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,3,0,3.0,0.0,0,0,0,2,0,3,0,0
1,1,1,4.0,3.0,1,1,2,2,1,3,2,0
2,3,1,3.0,0.0,0,0,1,1,2,9,0,0
3,1,1,4.0,2.0,1,0,2,2,3,5,2,0
4,3,0,4.0,0.0,0,0,0,1,3,9,0,2

In [51]:
drop_features = ["PassengerId", "Survived"]
df_onehot = df_onehot.drop(drop_features, axis=1).copy()
df_onehot.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,3,0,3.0,0.0,0,0,0,2,0,3,0,0
1,1,1,4.0,3.0,1,1,2,2,1,3,2,0
2,3,1,3.0,0.0,0,0,1,1,2,9,0,0
3,1,1,4.0,2.0,1,0,2,2,3,5,2,0
4,3,0,4.0,0.0,0,0,0,1,3,9,0,2

In [54]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [56]:
df_label = df_label.apply(LabelEncoder().fit_transform)

In [58]:
df_label.head() #라벨인코더 방식으로 모든 전 데이터가 동일한 메뉴얼 규칙에 적용 => 0부터 시작, 정수타입

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,2,0,3,0,0,0,0,1,0,3,0,0
1,0,1,4,3,1,1,2,1,1,3,2,0
2,2,1,3,0,0,0,1,0,2,9,0,0
3,0,1,4,2,1,0,2,1,3,5,2,0
4,2,0,4,0,0,0,0,0,3,9,0,2

In [60]:
onehot_cols = df_label.columns.tolist()

In [61]:
onehot_cols

['Pclass',
 'Sex',
 'Age',
 'Fare',
 'Cabin',
 'Embarked',
 'Initial',
 'Family',
 'Ticket_Initial2',
 'Ticket_Num_Cut',
 'HighChance',
 'LowChance']

In [62]:
df_onehot = pd.get_dummies(df_label, columns= onehot_cols)

In [65]:
df_onehot.head()

,Pclass_0,Pclass_1,Pclass_2,Sex_0,Sex_1,Age_0,Age_1,Age_2,Age_3,Age_4,...,HighChance_0,HighChance_1,HighChance_2,HighChance_3,HighChance_4,HighChance_5,HighChance_6,LowChance_0,LowChance_1,LowChance_2
0,False,False,True,True,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,False
1,True,False,False,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,True,False,False
2,False,False,True,False,True,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,False
3,True,False,False,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,True,False,False
4,False,False,True,True,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,True

In [67]:
df_onehot = pd.get_dummies(df_label, columns=onehot_cols, dtype=int)

In [68]:
df_onehot.head()

,Pclass_0,Pclass_1,Pclass_2,Sex_0,Sex_1,Age_0,Age_1,Age_2,Age_3,Age_4,...,HighChance_0,HighChance_1,HighChance_2,HighChance_3,HighChance_4,HighChance_5,HighChance_6,LowChance_0,LowChance_1,LowChance_2
0,0,0,1,1,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
4,0,0,1,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [71]:
import pickle

with open("titanic_step3_feature_encoding.pickle", "wb") as pickle_filename: 
    pickle.dump(df_onehot,pickle_filename)

In [72]:
import pickle

with open("titanic_step3_feature_encoding_y.pickle", "wb") as pickle_filename: 
    pickle.dump(y_train,pickle_filename)