In [12]:
import pandas as pd
import csv

df = pd.read_csv("UserResearch.csv", encoding="utf-8-sig")

df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte

In [11]:
df_freq= df[["연령대","Q. 편의점을 얼마나 자주 이용하시나요?"]].copy()

KeyError: "['Q. 편의점을 얼마나 자주 이용하시나요?'] not in index"

In [2]:
df.shape

(92, 25)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   성별                      92 non-null     object
 1   연령대                     92 non-null     object
 2   직업                      92 non-null     object
 3   이용빈도                    92 non-null     object
 4   이용목적                    92 non-null     object
 5   만족                      92 non-null     object
 6   불편                      92 non-null     object
 7   구매 포기 이유                92 non-null     object
 8   선호 매장 종류                92 non-null     object
 9   앱 사용 여부                 92 non-null     object
 10  앱 사용 목적                 53 non-null     object
 11  앱에서 가장 많이 사용하는 기능       54 non-null     object
 12  앱 불편한점                  54 non-null     object
 13  CU앱 신뢰도                 62 non-null     float64
 14  앱을 확인한 후 실제 매장을 방문한 경험  62 non-null     object
 15  쿠폰의 개인 취향 부합 정도         60 non-null     float64
 16  쿠폰 미사용 이유               62 non-null     object
 17  희망 쿠폰 종류                92 non-null     object
 18  쿠폰의 매장 방문 결정 영향         92 non-null     int64
 19  서비스 도입 후 편의점 편의성        92 non-null     int64
 20  재방문 주요 이유               92 non-null     object
 21  서비스 도입 후 CU 선택 영향       92 non-null     int64
 22  1회 평균 지출 금액             92 non-null     object
 23  계획에 없던 상품을 추가로 구매할 의향   92 non-null     int64
 24  지인에게 추천할 의향             92 non-null     int64
dtypes: float64(2), int64(5), object(18)
memory usage: 18.1+ KB

In [4]:
df.isnull().sum()

성별                         0
연령대                        0
직업                         0
이용빈도                       0
이용목적                       0
만족                         0
불편                         0
구매 포기 이유                   0
선호 매장 종류                   0
앱 사용 여부                    0
앱 사용 목적                   39
앱에서 가장 많이 사용하는 기능         38
앱 불편한점                    38
CU앱 신뢰도                   30
앱을 확인한 후 실제 매장을 방문한 경험    30
쿠폰의 개인 취향 부합 정도           32
쿠폰 미사용 이유                 30
희망 쿠폰 종류                   0
쿠폰의 매장 방문 결정 영향            0
서비스 도입 후 편의점 편의성           0
재방문 주요 이유                  0
서비스 도입 후 CU 선택 영향          0
1회 평균 지출 금액                0
계획에 없던 상품을 추가로 구매할 의향      0
지인에게 추천할 의향                0
dtype: int64

In [9]:
df.columns

Index(['타임스탬프',
       '[필수동의] 개인정보 수집 및 이용 동의\n본 설문은 익명으로 진행됩니다. 응답 내용은 통계 분석용으로만 사용되며, 어떠한 개인정보도 외부에 공개되지 않습니다. \n단, 추후 베타서비스(테스트 페이지)를 경험해보고 싶은 희망자에 한해 이메일 주소를 수집할 수 있습니다.',
       '성별', '연령대', '직업', '  Q. 편의점을 얼마나 자주 이용하시나요?  ',
       ' Q. 편의점을 이용하는 목적은 무엇인가요? (복수 선택 가능)',
       '  Q. CU 매장을 이용하며 만족스러웠던 점은 무엇인가요?  (복수 선택 가능)',
       '  Q. CU 매장을 이용하며 불편함을 느낀 경험이 있다면 무엇인가요?  (복수 선택 가능)',
       'Q . CU 매장에서 상품 구매를 포기하거나 헛걸음을 한 경험이 있다면, 그 이유는 무엇인가요?  ',
       '  Q. 무인 매장과 유인 매장 중 어떤 형태를 더 선호하시나요?  ',
       '  Q. 편의점 어플리케이션을 사용하고 계신가요?  ', 'Q. 편의점 앱을 사용하는 목적은 무엇인가요? (복수 선택 가능)',
       'Q. 앱 실행 시 가장 많이 사용하는 기능은 무엇인가요?',
       'Q. 편의점 앱 사용 시 불편하게 느끼는 점은 무엇인가요? (복수 선택 가능)',
       'Q. 포켓CU 앱에서 제공하는 상품 및 재고 정보에 대해 얼마나 신뢰하시나요?',
       'Q. 앱(쿠폰, 재고 등)을 확인한 후 실제 매장을 방문한 경험이 있으신가요?',
       'Q. 앱에서 제공되는 쿠폰이 본인의 구매 취향이나 관심사에 얼마나 부합한다고 느끼시나요?',
       'Q. 제공된 쿠폰을 사용하지 않는 경우, 이유는 무엇인가요? (복수 선택 가능)',
       'Q. 어떤 상품 카테고리의 쿠폰을 가장 받고 싶으신가요?', 'Q. 쿠폰이 매장 방문 결정에 얼마나 영향을 미치나요?',
       'Q. 개인화된 추천 및 혜택(쿠폰, 재고 알림 등)이 제공된다면 편의점 이용 편의성이 얼마나 향상될 것으로 예상하시나요?\n (예시: 구매 이력/관심상품/둘러본 제품 기반 개인 맞춤형 상품 추천 및 쿠폰, 현재 위치 기반 가까운 매장의 상품 입고/품절 임박 알림, 실시간 재고 확정 및 선점 예약)',
       'Q. CU를 재방문하게 되는 경우, 주요 이유는 무엇인가요?',
       'Q. CU가 개인화된 서비스를 제공할 경우, 다른 편의점과 거리가 비슷한 상황에서 CU 선택에 얼마나 영향을 미칠 것 같으신가요?',
       '  Q. 편의점 이용 시 1회 평균 지출 금액은 어느 정도인가요?  ',
       '  Q. 관심 상품에 대한 맞춤형 할인 쿠폰이 제공될 경우, 계획에 없던 상품을 추가로 구매할 의향이 있으신가요?  ',
       '베타 서비스 참여 안내\n본 프로젝트에서는 향후 **베타 서비스(테스트 페이지)**를 통해 새로운 편의점 이용 경험을 체험해볼 수 있는 기회를 제공할 예정입니다.\n참여를 희망하시는 분들 중 일부를 추첨하여 **소정의 상품을 제공해 드립니다.\n해당 테스트에 참여를 원하시는 분들께서는 아래에 이메일을 남겨주시면 추후 별도로 안내드리겠습니다.',
       'Q. CU가 이러한 데이터 기반 서비스를 먼저 도입한다면, 지인에게 추천할 의향은 어느 정도인가요?',
       'Q. 편의점 앱을 사용하고 계신가요?', '27열'],
      dtype='object')

In [7]:
df["성별"].value_counts()

성별
남자    48
여자    44
Name: count, dtype: int64

In [8]:
df["연령대"].value_counts()

연령대
20대       49
30대       30
50대 이상     9
40대        4
Name: count, dtype: int64

In [9]:
# 교차분석 : 연령대별 이용 빈도

age_frequency = pd.crosstab(df["연령대"], df["이용빈도"])

age_frequency

이용빈도    월 1-2회  이용하지 않음  주 1-2회  주 3-5회  주 6회 이상
연령대
20대          4        1      18      18        8
30대         11        0      10       8        1
40대          0        0       2       1        1
50대 이상       5        0       4       0        0

In [23]:
target_elements = ['주 6회 이상', '주 3-5회']

filtered_df = df[df['이용빈도'].isin(target_elements)]

In [28]:
# 필터링된 데이터로 그룹화 및 집계
analysis_gb = filtered_df.groupby(['성별', '연령대', '이용빈도']).size().reset_index(name='응답수')

# 응답수 기준 내림차순 정렬
analysis_gb_sorted = analysis_gb.sort_values(by='응답수', ascending=False)

analysis_gb_sorted

   성별  연령대     이용빈도  응답수
0  남자  20대   주 3-5회   11
6  여자  20대   주 3-5회    7
1  남자  20대  주 6회 이상    6
2  남자  30대   주 3-5회    4
8  여자  30대   주 3-5회    4
7  여자  20대  주 6회 이상    2
3  남자  30대  주 6회 이상    1
4  남자  40대   주 3-5회    1
5  남자  40대  주 6회 이상    1

In [35]:
# 2. 비율 계산 (normalize=True) 및 데이터프레임 변환
# value_counts는 기본적으로 내림차순 정렬을 수행합니다.
ratio_df = filtered_df[['성별', '연령대', '이용빈도']].value_counts(normalize=True).reset_index(name='비율(%)')

# 3. 소수점을 백분율(%)로 변환
ratio_df['비율(%)'] = ratio_df['비율(%)'] * 100

# 4. 명시적으로 내림차순 정렬 (이미 되어있지만 확실히 하기 위해)
ratio_df = ratio_df.sort_values(by='비율(%)', ascending=False)

print(ratio_df)

   성별  연령대     이용빈도      비율(%)
0  남자  20대   주 3-5회  29.729730
1  여자  20대   주 3-5회  18.918919
2  남자  20대  주 6회 이상  16.216216
3  남자  30대   주 3-5회  10.810811
4  여자  30대   주 3-5회  10.810811
5  여자  20대  주 6회 이상   5.405405
6  남자  30대  주 6회 이상   2.702703
7  남자  40대   주 3-5회   2.702703
8  남자  40대  주 6회 이상   2.702703

In [41]:
# 분석할 대상 컬럼 리스트
target_cols = [
    '쿠폰의 매장 방문 결정 영향', 
    '계획에 없던 상품을 추가로 구매할 의향'
]

# groupby를 활용해 성별과 연령대별 평균 계산
# .round(1)을 붙여 소수점 첫째 자리까지만 표시합니다.
final_analysis = df.groupby(['성별', '연령대'])[target_cols].mean().round(1)

# 결과 확인
print(final_analysis)

           쿠폰의 매장 방문 결정 영향  계획에 없던 상품을 추가로 구매할 의향
성별 연령대
남자 20대                 3.7                    3.9
   30대                 3.6                    3.6
   40대                 3.7                    3.7
   50대 이상              2.2                    2.8
여자 20대                 3.9                    3.9
   30대                 3.0                    3.6
   40대                 3.0                    4.0
   50대 이상              4.2                    3.8

In [46]:
df["1회 평균 지출 금액"]

0     5.000100e+08
1     5.000000e+03
2     5.000100e+08
3     1.000030e+09
4     5.000100e+08
          ...
87    5.000100e+08
88    1.000030e+09
89    1.000030e+09
90    5.000100e+08
91    1.000030e+09
Name: 1회 평균 지출 금액, Length: 92, dtype: float64

In [51]:
# 매핑 딕셔너리 생성
correct_labels = {
    5.000000e+03: '5,000원 미만',
    5.000100e+08: '5,000~10,000원 미만',
    1.000030e+09: '10,000~30,000원 미만',
    3.000050e+09: '30,000~50,000원 미만'
}

# 데이터프레임의 값을 실제 이름으로 치환
# 만약 'spending_counts'라는 변수에 집계 결과가 있다면:
df['1회 평균 지출 금액'] = df['1회 평균 지출 금액'].map(correct_labels)

# 결과 확인
print(df['1회 평균 지출 금액'])

0      5,000~10,000원 미만
1             5,000원 미만
2      5,000~10,000원 미만
3     10,000~30,000원 미만
4      5,000~10,000원 미만
            ...
87     5,000~10,000원 미만
88    10,000~30,000원 미만
89    10,000~30,000원 미만
90     5,000~10,000원 미만
91    10,000~30,000원 미만
Name: 1회 평균 지출 금액, Length: 92, dtype: object

In [52]:
# 성별, 연령대별로 지출 금액 범주의 빈도 계산
spending_counts = df.groupby(['성별', '연령대', '1회 평균 지출 금액']).size().reset_index(name='응답수')

# 응답수 기준 내림차순 정렬
spending_counts = spending_counts.sort_values(by='응답수', ascending=False)

print(spending_counts.head(10)) # 상위 10개 조합 확인

    성별     연령대        1회 평균 지출 금액  응답수
1   남자     20대   5,000~10,000원 미만   20
16  여자     30대   5,000~10,000원 미만   15
2   남자     20대          5,000원 미만   12
13  여자     20대   5,000~10,000원 미만    8
14  여자     20대          5,000원 미만    6
3   남자     30대  10,000~30,000원 미만    5
17  여자     30대          5,000원 미만    5
20  여자  50대 이상          5,000원 미만    3
19  여자  50대 이상  10,000~30,000원 미만    2
5   남자     30대          5,000원 미만    2

In [65]:
# 이미 변환되기 전의 원본 df가 있다면 이 코드가 가장 안전합니다.
analysis = df.groupby(['성별', '연령대', '1회 평균 지출 금액']).size().reset_index(name='응답수')
analysis = analysis.sort_values(by='응답수', ascending=False)

analysis.head(10)

    성별     연령대        1회 평균 지출 금액  응답수
1   남자     20대   5,000~10,000원 미만   20
16  여자     30대   5,000~10,000원 미만   15
2   남자     20대          5,000원 미만   12
13  여자     20대   5,000~10,000원 미만    8
14  여자     20대          5,000원 미만    6
3   남자     30대  10,000~30,000원 미만    5
17  여자     30대          5,000원 미만    5
20  여자  50대 이상          5,000원 미만    3
19  여자  50대 이상  10,000~30,000원 미만    2
5   남자     30대          5,000원 미만    2

In [10]:
# 이미 변환되기 전의 원본 df가 있다면 이 코드가 가장 안전합니다.
analysis = df.groupby(['성별', '1회 평균 지출 금액']).size().reset_index(name='응답수')
analysis = analysis.sort_values(by='응답수', ascending=False)

analysis.head(10)

KeyError: '1회 평균 지출 금액'

In [54]:
# 교차분석 : 연령대별 앱 사용 여부

age_appuse = pd.crosstab(df["연령대"], df["앱 사용 여부"])

age_appuse

앱 사용 여부  사용중  사용하지 않음
연령대
20대       16       33
30대       12       18
40대        1        3
50대 이상     1        8

In [55]:
# 교차분석 : 연령대별 선호 매장 종류

age_store = pd.crosstab(df["연령대"], df["선호 매장 종류"])

age_store

선호 매장 종류  무인 매장  상관없음  유인 매장
연령대
20대           7    19     23
30대           1    16     13
40대           1     0      3
50대 이상        0     3      6

In [56]:
# 교차분석 : 연령대별 1회 평균 지출 금액

age_cost = pd.crosstab(df["연령대"], df["1회 평균 지출 금액"])

age_cost

1회 평균 지출 금액  10,000~30,000원 미만  30,000~50,000원 미만  5,000~10,000원 미만  5,000원 미만
연령대
20대                          2                  1                28         18
30대                          7                  0                16          7
40대                          3                  0                 1          0
50대 이상                       3                  0                 2          4

In [57]:
# 교차분석 : 재방문 주요 이유가 위치 접근성이었던 고객이 서비스 도입 후 변화할 가능성

coupon_bf_at = pd.crosstab(df["서비스 도입 후 CU 선택 영향"], df["재방문 주요 이유"])

coupon_bf_at

재방문 주요 이유          가격 경쟁력  상품 다양성  위치 접근성  프로모션/행사
서비스 도입 후 CU 선택 영향
1                       0       0       2        0
2                       0       0       4        0
3                       4       3      17        5
4                       3       6      22        5
5                       1       3      15        2

In [58]:
# 교차분석 : 객단가 상승 가능성

coupon_use_cost = pd.crosstab(df["1회 평균 지출 금액"], df["계획에 없던 상품을 추가로 구매할 의향"])

coupon_use_cost

계획에 없던 상품을 추가로 구매할 의향  2   3   4   5
1회 평균 지출 금액
10,000~30,000원 미만      0   5   8   2
30,000~50,000원 미만      0   0   0   1
5,000~10,000원 미만       4  11  21  11
5,000원 미만              6   5  14   4

In [63]:
# 점수분석 :

df["CU앱 신뢰도"].describe()

count    62.000000
mean      3.338710
std       0.922284
min       1.000000
25%       3.000000
50%       3.000000
75%       4.000000
max       5.000000
Name: CU앱 신뢰도, dtype: float64

In [64]:
# 점수분석 :

df["쿠폰의 개인 취향 부합 정도"].describe()

count    60.000000
mean      2.616667
std       0.825272
min       1.000000
25%       2.000000
50%       3.000000
75%       3.000000
max       4.000000
Name: 쿠폰의 개인 취향 부합 정도, dtype: float64

In [65]:
# 점수분석 :

df["쿠폰의 매장 방문 결정 영향"].describe()

count    92.000000
mean      3.521739
std       1.123948
min       1.000000
25%       3.000000
50%       4.000000
75%       4.000000
max       5.000000
Name: 쿠폰의 매장 방문 결정 영향, dtype: float64

In [66]:
# 점수분석 :

df["서비스 도입 후 편의점 편의성"].describe()

count    92.00000
mean      3.75000
std       0.95647
min       1.00000
25%       3.00000
50%       4.00000
75%       4.00000
max       5.00000
Name: 서비스 도입 후 편의점 편의성, dtype: float64

In [67]:
# 점수분석 :

df["서비스 도입 후 CU 선택 영향"].describe()

count    92.000000
mean      3.760870
std       0.930196
min       1.000000
25%       3.000000
50%       4.000000
75%       4.000000
max       5.000000
Name: 서비스 도입 후 CU 선택 영향, dtype: float64

In [68]:
# 점수분석 :

df["계획에 없던 상품을 추가로 구매할 의향"].describe()

count    92.000000
mean      3.750000
std       0.897187
min       2.000000
25%       3.000000
50%       4.000000
75%       4.000000
max       5.000000
Name: 계획에 없던 상품을 추가로 구매할 의향, dtype: float64

In [69]:
# 점수분석 :

df["지인에게 추천할 의향"].describe()

count    92.000000
mean      3.521739
std       0.844872
min       1.000000
25%       3.000000
50%       4.000000
75%       4.000000
max       5.000000
Name: 지인에게 추천할 의향, dtype: float64

In [67]:
import pandas as pd

# 1. 분석 대상 그룹 설정 (작성해주신 순서 기준)
target_groups = [
    ('남자', '20대'), 
    ('여자', '20대'), 
    ('남자', '30대'), 
    ('여자', '30대')
]

# 2. 분석할 컬럼
analysis_cols = ['계획에 없던 상품을 추가로 구매할 의향', '서비스 도입 후 CU 선택 영향']

# 3. 데이터 필터링 및 평균 계산
# 성별과 연령대를 인덱스로 설정하면 멀티인덱스 조회가 편합니다.
group_stats = df.groupby(['성별', '연령대'])[analysis_cols].mean()

# 4. 순위에 맞춰서 결과 재배치
ranked_analysis = group_stats.loc[target_groups].round(2)

# 5. 가독성을 위해 순위 인덱스 추가
ranked_analysis.index = ['1순위(20대 남)', '2순위(20대 여)', '공동 3순위(30대 남)', '공동 3순위(30대 여)']

print(ranked_analysis)

               계획에 없던 상품을 추가로 구매할 의향  서비스 도입 후 CU 선택 영향
1순위(20대 남)                      3.88               3.88
2순위(20대 여)                      3.94               4.25
공동 3순위(30대 남)                   3.62               3.25
공동 3순위(30대 여)                   3.64               3.82