In [1]:
import pandas as pd

# python에서는 {} -> 딕셔너리, [] -> 리스트로 취급해옴
#but pandas체계에서는 아님 
#C
df = pd.DataFrame({  #복수의 대괄호(시리즈)를 감싸기 위한 {} 
    "미국": [2.1, 2.2, 2.3],    #시리즈를 식별할 수 있는 이름이 필요해짐
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]
})

In [5]:
df

    미국    한국  중국
0  2.1  0.40  10
1  2.2  0.50  13
2  2.3  0.45  15

In [84]:
#index명이 변경된 것처럼 보이지만, 오리지널은 0부터 1씩 증가하는 속성을 가짐. 간판만 갈아낀 것 뿐 
df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],   
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15],
},index=[2000,2010,2020])

In [11]:
df.index

Index([2000, 2010, 2020], dtype='int64')

In [86]:
df.index = [2001, 2002, 2003]

In [87]:
df

       미국    한국  중국
2001  2.1  0.40  10
2002  2.2  0.50  13
2003  2.3  0.45  15

In [14]:
df.columns   #--> 속성! 주소값을 직접 찾아변경하는 것이기 때문에  밑에서 변경했을때 바로 실제 값이 변경됨

Index(['미국', '한국', '중국'], dtype='object')

In [17]:
df.columns = ["일본", "필리핀", "러시아"]

In [18]:
df

       일본   필리핀  러시아
2001  2.1  0.40   10
2002  2.2  0.50   13
2003  2.3  0.45   15

In [19]:
df.values #하나의 행을 대괄호로 표기

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [21]:
df = pd.DataFrame({
    "년도": [2000, 2010, 2020],
    "미국": [2.1, 2.2, 2.3],   
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15],
})

In [22]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [23]:
#시리즈 값을 인덱스로 변경하기
df.set_index("년도")   
#-> 매서드 함수! 실제 주소를 찾아오는게 아니라 기능을 수행하는 것. 따라서 변경해도 그 주소가 실제로 바뀌는게 아니라 기능에 따라 일시적으로 변경된 값이 출력되는 것 뿐!!
#-> 실제 주소를 변경하려면 df 재할당이 필요함

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [29]:
df = df.set_index("년도")

In [30]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [31]:
#인덱스 값 변경하기 -> 찾아오는게 먼저
df.index.name

'년도'

In [33]:
df.index.name = "연도"

In [34]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [36]:
df = df.reset_index("연도")

In [37]:
df

     연도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [38]:
df= df.set_index("연도")
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [39]:
df.loc[2000]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [40]:
df.iloc[0]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [41]:
type(df.loc[2000])

pandas.core.series.Series

In [42]:
#열을 찾아올때
df["미국"]

연도
2000    2.1
2010    2.2
2020    2.3
Name: 미국, dtype: float64

In [48]:
#중첩방식으로 값 찾아오기
print(df["미국"][2000])  #열방식
print(df.loc[2000]["미국"]) #행방식
print(df.iloc[0]["미국"])

2.1
2.1
2.1

In [49]:
df = pd.DataFrame({
    "년도": ["2000", "2010", "2020"],
    "미국": [2.1, 2.2, 2.3],   
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15],
})
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [50]:
df= df.set_index("년도")

In [53]:
# df.loc[2000]  #--> 오류:2000은 정수가 아닌 문자열
df.loc["2000"]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [54]:
df.columns

Index(['미국', '한국', '중국'], dtype='object')

In [56]:
df["일본"] = [1, 2, 3]

In [57]:
df

       미국    한국  중국  일본
년도
2000  2.1  0.40  10   1
2010  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [58]:
del df["일본"]

In [59]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [69]:
#인덱스기반 추가 
df.loc["2021"] = [1, 2, 3]
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2021  1.0  2.00   3

In [62]:
df.drop(["2021"])

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [68]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [70]:
df = df.drop(["2021"])
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [71]:
df = df.reset_index("년도")
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [73]:
#데이터에서 특정 시리즈값만 결합한 새로운 데이터 프레임 생성
df2 = df[["한국","중국"]].copy()

In [74]:
df2

     한국  중국
0  0.40  10
1  0.50  13
2  0.45  15

In [75]:
df2.columns

Index(['한국', '중국'], dtype='object')

In [78]:
df2.columns = ["브라질", "아르헨티나"]

In [83]:
df2["년도"] = [2000, 2010, 2020]

TypeError: 'method' object does not support item assignment

In [80]:
df2 = df2.set_index
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [ ]:
#깊은복사, 얕은복사 => stack, que, deque => c/s