In [ ]:
#pandas 활용, 데이터 전처리 > 정제 시, 꼭 알고 있어야하는 문제해결 방법

#1. 전체 데이터의 사이즈, 결측치 정보             ==> size,shape,info(),count
#2. 결측치 발생 시 대처방안                      ==> fillna(), dropna()
#3. 특정 조건에 해당되는 값찾기                   ==>  doc[doc.index == "US"]
#4. 특정 컬럼만 값 찾아오기                      ==> covid_stat = doc[["Confirmed", "Deaths",	"Recovered"]]
#5. 타입 변경시, 결측치부터 해결                 ==>  doc2 = doc2.astype({"Confirmed": "int64"})
#6. 서로 다른 데이터 연결시, 동일한 필드명 통일   ==> doc3.columns= ["Country_Region", "Confirmed"]
#7. 중복값 존재시 삭제.제거                     ==> doc4= doc4.drop_duplicates(subset="Country_Region")

In [3]:
import pandas as pd

df1 = pd.DataFrame({
    "id":[1,2,3],
    "customer_id":[1,2,3],
    "customer_name":["Robert", "Peter", "Dave"],
})

In [2]:
df1

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3          Dave

In [4]:
import pandas as pd

df2 = pd.DataFrame({
    "id":[1,2,4],
    "order_id":[100,200,300],
    "order_date": ["2021-01-21", "2021-02-03", "2020-10-01"],
    "customer_name":["Robert", "Peter", "Dave"],
})

In [5]:
df2

   id  order_id  order_date customer_name
0   1       100  2021-01-21        Robert
1   2       200  2021-02-03         Peter
2   4       300  2020-10-01          Dave

In [ ]:
#concat() : 두개의 데이터 프레임을 연결해서 하나의 데이터프레임으로 만드는 방법

In [6]:
pd.concat([df1,df2])

   id  customer_id customer_name  order_id  order_date
0   1          1.0        Robert       NaN         NaN
1   2          2.0         Peter       NaN         NaN
2   3          3.0          Dave       NaN         NaN
0   1          NaN        Robert     100.0  2021-01-21
1   2          NaN         Peter     200.0  2021-02-03
2   4          NaN          Dave     300.0  2020-10-01

In [7]:
df1 #덮어쓰지 않아서 그대로 살아있음

   id  customer_id customer_name
0   1            1        Robert
1   2            2         Peter
2   3            3          Dave

In [8]:
df2

   id  order_id  order_date customer_name
0   1       100  2021-01-21        Robert
1   2       200  2021-02-03         Peter
2   4       300  2020-10-01          Dave

In [9]:
pd.concat([df1,df2], axis = 1)  #axis : 축. 옵션 셜정x = 0 -> 0(default값, 위아래로 연결해라)
                                                        #-> axis = 1 (좌우로 연결해라)

   id  customer_id customer_name  id  order_id  order_date customer_name
0   1            1        Robert   1       100  2021-01-21        Robert
1   2            2         Peter   2       200  2021-02-03         Peter
2   3            3          Dave   4       300  2020-10-01          Dave

In [10]:
pd.merge(df1,df2)   ##-> innerjoin 느낌

   id  customer_id customer_name  order_id  order_date
0   1            1        Robert       100  2021-01-21
1   2            2         Peter       200  2021-02-03