In [ ]:
#지금까지 내용 문법 정리

In [6]:
# pandas 파일 로드

import pandas as pd
doc = pd.read_csv("00_data/olist_customers_dataset.csv", encoding="utf-8-sig")
doc.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
#데이터 사이즈
doc.shape

(99441, 5)

In [8]:
#데이터 상세명세서 확인
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [9]:
#데이터 필드명 및 컬럼목록

doc.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [10]:
#데이터 인덱스(측정기준)
doc.index

RangeIndex(start=0, stop=99441, step=1)

In [11]:
#데이터 5 numbers summary

doc.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [12]:
#데이터 상위 5개 확인
doc.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [15]:
#raw 데이터에서 필요하다고 판단되는 컬럼만 별도로 추출해서 가져오기

doc2 = doc[["customer_zip_code_prefix","customer_city","customer_state"]].copy()
doc2

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 3 columns]

In [20]:
#현재 카피해온 데이터프레임 안에서 특정 조건에 해당되는 값만 추출해오자

doc3 = doc2[doc2["customer_city"] == "sao paulo"]
doc3.shape

(15540, 3)

In [22]:
#특정 데이터프레임 내, 컬럼을 기준으로 값의 갯수 확인
doc2["customer_city"].value_counts()

customer_city
sao paulo                   15540
rio de janeiro               6882
belo horizonte               2773
brasilia                     2131
curitiba                     1521
                            ...
olhos d'agua                    1
pacotuba                        1
sao sebastiao do paraiba        1
benedito leite                  1
campos verdes                   1
Name: count, Length: 4119, dtype: int64

In [25]:
# 특정 데이터 프레인 내, 그룹화 (그룹화 대상 =인덱스)
doc4 = doc2.groupby("customer_city").count()
doc4

                     customer_zip_code_prefix  customer_state
customer_city
abadia dos dourados                         3               3
abadiania                                   1               1
abaete                                     12              12
abaetetuba                                 11              11
abaiara                                     2               2
...                                       ...             ...
xinguara                                    9               9
xique-xique                                 3               3
zacarias                                    2               2
ze doca                                     5               5
zortea                                      2               2

[4119 rows x 2 columns]

In [26]:
#특정 데이터프레임 내 인덱스의 길이 확인

len(doc4.index)
doc4.shape

(4119, 2)

In [27]:
#특정 데이터프레임 내 상위 5개문서 조회
doc4.head()

                     customer_zip_code_prefix  customer_state
customer_city
abadia dos dourados                         3               3
abadiania                                   1               1
abaete                                     12              12
abaetetuba                                 11              11
abaiara                                     2               2

In [28]:
doc4 = doc.groupby("customer_city").count()
doc4

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
customer_city,,,,
abadia dos dourados,3,3,3,3
abadiania,1,1,1,1
abaete,12,12,12,12
abaetetuba,11,11,11,11
abaiara,2,2,2,2
...,...,...,...,...
xinguara,9,9,9,9
xique-xique,3,3,3,3
zacarias,2,2,2,2
ze doca,5,5,5,5
zortea,2,2,2,2

In [33]:
#특정 데이터 프레임 내 컬럼을 기준으로 정렬
# doc4["cutomer_id"].sort_values(ascending =True)
doc4["customer_id"].sort_values(ascending =False).head(1)

customer_city
sao paulo    15540
Name: customer_id, dtype: int64

In [36]:
doc4.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
customer_city,,,,
abadia dos dourados,3,3,3,3
abadiania,1,1,1,1
abaete,12,12,12,12
abaetetuba,11,11,11,11
abaiara,2,2,2,2

In [37]:
#데이터 프레임 내 인덱스를 새롭게 적용
doc4.set_index("customer_id")

             customer_unique_id  customer_zip_code_prefix  customer_state
customer_id
3                             3                         3               3
1                             1                         1               1
12                           12                        12              12
11                           11                        11              11
2                             2                         2               2
...                         ...                       ...             ...
9                             9                         9               9
3                             3                         3               3
2                             2                         2               2
5                             5                         5               5
2                             2                         2               2

[4119 rows x 3 columns]

In [38]:
doc.set_index("customer_city")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
customer_city,,,,
franca,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,SP
sao bernardo do campo,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,SP
sao paulo,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,SP
mogi das cruzes,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,SP
campinas,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,SP
...,...,...,...,...
sao paulo,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,SP
taboao da serra,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,SP
fortaleza,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,CE
canoas,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,RS
cotia,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,SP

In [40]:
#데이터프레임 > 인덱스 내 정렬
doc.set_index("customer_city").sort_index()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
customer_city,,,,
abadia dos dourados,a23e3f9a2b656b23b7e52075964b42cd,afddf43a03a9941624ed42c0b2c17280,38540,MG
abadia dos dourados,9e01f714a2b3b8962c222cf2b74c20dc,e1feae9083c4c2895ddf6dc80526a85d,38540,MG
abadia dos dourados,f11eb8f0b8b87510a93e3e1aa10b0ade,64ee476500a01beb94df40f97a108c50,38540,MG
abadiania,576d71ddb21b21763cfedce73b902180,8d76b559181609308fcae630ea64cd61,72940,GO
abaete,5e9e1ae42e02df93e9a591e86fd531a3,28af9604f7830ef6d1230fb575c39eb1,35620,MG
...,...,...,...,...
ze doca,1052e334b46dd1e9876946d6372a363e,c933181d09535cb6bdfb1c0160323bd9,65365,MA
ze doca,d8b3ef6f73de33ae716e94d2478cc080,9ef06526b8e57a567ed6f1dce7ab0320,65365,MA
ze doca,fc87e5c06780700952aa42998a22968f,d4798889fe74026a739ca0be9d2dccb8,65365,MA
zortea,0a466d490a3c2fcc1e7177f4809ec7dd,d5a5ceb83234eeb855268d7fce7f54ea,89633,SC
zortea,e046f992a304cc92e1b00d7fccdf1c42,09a3f87b74828b274d73ee9dfef43b68,89633,SC

In [41]:
doc2

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 3 columns]

In [45]:
doc2["customer_state"].value_counts().shape

(27,)

In [49]:
#특정 데이터 프레임 안에서 인덱그 요소를 해제하고 원래 컴럼자
doc4 = doc4.reset_index()
doc4

,index,customer_city,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
0,0,abadia dos dourados,3,3,3,3
1,1,abadiania,1,1,1,1
2,2,abaete,12,12,12,12
3,3,abaetetuba,11,11,11,11
4,4,abaiara,2,2,2,2
...,...,...,...,...,...,...
4114,4114,xinguara,9,9,9,9
4115,4115,xique-xique,3,3,3,3
4116,4116,zacarias,2,2,2,2
4117,4117,ze doca,5,5,5,5
4118,4118,zortea,2,2,2,2

In [50]:
doc4[doc4["customer_id"] > 1000].shape

(9, 6)

In [88]:
doc4 = doc4.set_index("customer_city")
doc4

,level_0,index,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
customer_city,,,,,,
abadia dos dourados,0,0,3,3,3,3
abadiania,1,1,1,1,1,1
abaete,2,2,12,12,12,12
abaetetuba,3,3,11,11,11,11
abaiara,4,4,2,2,2,2
...,...,...,...,...,...,...
xinguara,4114,4114,9,9,9,9
xique-xique,4115,4115,3,3,3,3
zacarias,4116,4116,2,2,2,2
ze doca,4117,4117,5,5,5,5
zortea,4118,4118,2,2,2,2

In [89]:
doc4[doc4["customer_id"] > 1000].index

Index(['belo horizonte', 'brasilia', 'campinas', 'curitiba', 'guarulhos',
       'porto alegre', 'rio de janeiro', 'salvador', 'sao paulo'],
      dtype='object', name='customer_city')

In [90]:
doc4 = doc4.reset_index()
doc4

,customer_city,level_0,index,customer_id,customer_unique_id,customer_zip_code_prefix,customer_state
0,abadia dos dourados,0,0,3,3,3,3
1,abadiania,1,1,1,1,1,1
2,abaete,2,2,12,12,12,12
3,abaetetuba,3,3,11,11,11,11
4,abaiara,4,4,2,2,2,2
...,...,...,...,...,...,...,...
4114,xinguara,4114,4114,9,9,9,9
4115,xique-xique,4115,4115,3,3,3,3
4116,zacarias,4116,4116,2,2,2,2
4117,ze doca,4117,4117,5,5,5,5
4118,zortea,4118,4118,2,2,2,2

In [91]:
#데이터프레임 내 결측지 존재 여부 확인

doc.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [92]:
#수집된 데이터를 기반으로 리스트 변경하기

# doc.drop_duplicates(subset="customer_city", keep="first") #first

: 중복값 중 최초값, last : 중복값 중 최종값
doc.drop_duplicates(subset="customer_city", keep="first")["customer_city.to_list()"] #first: 중복값 중 최초값, last : 중복값 중 최종값

KeyError: 'customer_city.to_list()'

In [62]:
#피봇테이블 = > 기존데이터에서 내가 추가적으로 필터링을 해서 값을 찾아오는 것

import pandas as pd
doc_covid = pd.read_csv("COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv", encoding="utf-8-sig")
doc_covid.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [68]:
import pandas as pd

doc_covid2 = pd.pivot_table(doc_covid, index=["Country_Region"], values=["Confirmed"], aggfunc={"Confirmed":"median"}, fill_value=0)
doc_covid2.head()

                Confirmed
Country_Region
Afghanistan         192.0
Albania             259.0
Algeria             847.0
Andorra             390.0
Angola                8.0

In [78]:
import pandas as pd

doc_covid3 = pd.pivot_table(doc_covid,
                            index=["Country_Region"],
                            values=["Confirmed","Deaths"], 
                            aggfunc={"Confirmed":"sum","Deaths":"mean"}, 
                            fill_value=0,
                            margins=True,
                            margins_name="Total"
                           )
# doc_covid3.head()

In [79]:
doc_covid3

                      Confirmed     Deaths
Country_Region
Afghanistan                 192   4.000000
Albania                     259  15.000000
Algeria                     847  58.000000
Andorra                     390  14.000000
Angola                        8   2.000000
...                         ...        ...
West Bank and Gaza          134   1.000000
Winter Olympics 2022          0   0.000000
Zambia                       36   0.000000
Zimbabwe                      8   1.000000
Total                    938959  20.477002

[191 rows x 2 columns]

In [84]:
doc_covid3.style.format({
    "Confirmed": "{:,}",
    "Deaths" : "{:,.2f}"
})

In [81]:
doc_covid3[doc_covid3.index == "Total"]

                Confirmed     Deaths
Country_Region
Total              938959  20.477002